<a href="https://colab.research.google.com/github/ArvindReddyC/Sord_analysis/blob/main/Notebooks/Activity_prediction_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
!git clone https://github.com/ArvindReddyC/Sord_analysis.git

Cloning into 'Sord_analysis'...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 79 (delta 30), reused 45 (delta 10), pack-reused 0
Unpacking objects: 100% (79/79), done.

## Visualising for an varition in data

In [3]:
def encapsule(df):
    display(df.head(5))
    print( f'shape of df = {df.shape}' )
    return df

def tran(x):
    y = x[1:-1]
    return y.split(',')

def only_activities( df , list_of_activities_to_include ): 
    return df[ df.Activity.isin( list_of_activities_to_include ) ]


def data_wrangle( df ):
    sample = df[['timestamp','raw_sensor_data']];
    sample['parameters'] = sample.raw_sensor_data.apply(tran);
    main = pd.DataFrame( sample.parameters.to_list() , columns = ['v1','v2','v3','v4','v5','v6','v7','v8','v9','v10','v11'] );
    main['timestamp'] = sample['timestamp'];
    main.drop( 'v1' , axis = 1 , inplace = True );
    main.set_index('timestamp' , inplace=True);
    return main;


def removeprocess(x):
    try:
      main , *_  = x.split(' ')
    except (ValueError,AttributeError):
      return x
    return main

def val_counts(df):
    return df['Activity'].value_counts()
'''
Will t
'''
def groupby_avarage(activity_df):
    activity_df['Time'] =  activity_df.Time.astype(int)
    means_df = activity_df.groupby('Time').mean()
    mode_of_activities = []
    for each in activity_df.groupby('Time'):
        mode_of_activities.append(each[1]['Activity'].mode()[0])
    means_df['Activities'] = mode_of_activities
    return means_df


def process_sheet(df, number):
    df = df.fillna(method='ffill')
    df.drop( ['SORD', 'AP time' , 'AP classification'] , axis = 1 , inplace = True )
    df = only_activities( df , ['Standing', 'Sitting', 'Reclining' , 'Walking', 'Sitting (outsrtetched legs)'] )
    df['User_Id'] = number 
    df['Activity'] = df.Activity.apply(removeprocess)
    df.Activity = df.Activity.replace( 'Reclining' , 'Sitting' )  
    display(val_counts(df))
    return df


def process_sheet_edit(df, number):
    df = df.fillna(method='ffill')
    display(val_counts(df))
    df['Activity'] = df.Activity.apply(removeprocess)
    # df.drop( ['SORD', 'AP time' , 'AP classification'] , axis = 1 , inplace = True )
    df = only_activities( df , ['Standing', 'Sitting', 'Reclining' , 'Walking', 'Sitting'] )
    df['User_Id'] = number 
    df.Activity = df.Activity.replace( 'Reclining' , 'Sitting' )  
    display(val_counts(df))
    return df


def drop_un(df):
  try:
    df.drop( ['SORD', 'AP time' , 'AP classification'] , axis = 1 , inplace = True )
  except:
    return df 
  return df

In [4]:
Standing_df = encapsule(pd.read_csv('/content/Sord_analysis/Activity_files/Standing.csv'))

                                                                                                                id  ...                   updatedAt
722288 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2982.781144 77.386843 -9.68 -0.80 -2.16  1.2500 6.1875 -6.0625  ...  2022-02-22 07:41:52.312+00
722289 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2982.783205 77.087111 -9.39 -0.33 -2.27 -2.5625 7.7500 -4.6250  ...   2022-02-22 07:41:52.33+00
722290 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2982.784382 76.847067 -9.57 -0.76 -2.33  2.0000 4.6875 -3.2500  ...  2022-02-22 07:41:52.333+00
722291 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2982.785515 76.666880 -9.65 -0.33 -2.26  4.1875 9.7500 -4.3125  ...  2022-02-22 07:41:52.336+00
722292 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2982.786498 76.366269 -9.18 -0.71 -2.62  4.6250 3.8125 -4.1250  ...  2022-02-22 07:41:52.338+00

[5 rows x 9 columns]

shape of df = (15322, 9)

In [7]:
Standing_df['raw_sensor_data']

722288  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.781144  77.386843  -9.68  -0.80  -2.16   1.2500   6.1875     5.0625
722289  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.783205  77.087111  -9.39  -0.33  -2.27  -2.5625   7.7500     5.0625
722290  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.784382  76.847067  -9.57  -0.76  -2.33   2.0000   4.6875     5.5000
722291  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.785515  76.666880  -9.65  -0.33  -2.26   4.1875   9.7500     5.5000
722292  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.786498  76.366269  -9.18  -0.71  -2.62   4.6250   3.8125     4.2500
                                                                                                                         ...
738927  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.206852    88.947569  -9.76  -0.74  -0.11   3.6875  -0.1250    17.5625
738928  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.306089    89.006044  -9.76  -0.72  -0.19   0.1250  -0.6875    18.0000
738929  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.311593    89.006044  -9.77  -0.65  -0.31   3.9375   0.3125    18.0000
738930  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.315506    89.006044  -9.74  -0.62  -0.18   1.2500  -0.3125    16.6875
738931  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.353829    89.006044  -9.75  -0.73  -0.08   4.5000   0.2500    16.6875
Name: raw_sensor_data, Length: 15322, dtype: float64

In [8]:
Standing_df.iloc[:,1]

722288  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.781144  77.386843  -9.68  -0.80  -2.16   1.2500   6.1875   -49.8750
722289  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.783205  77.087111  -9.39  -0.33  -2.27  -2.5625   7.7500   -48.7500
722290  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.784382  76.847067  -9.57  -0.76  -2.33   2.0000   4.6875   -49.5000
722291  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.785515  76.666880  -9.65  -0.33  -2.26   4.1875   9.7500   -49.5000
722292  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  2982.786498  76.366269  -9.18  -0.71  -2.62   4.6250   3.8125   -49.5000
                                                                                                                         ...
738927  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.206852    88.947569  -9.76  -0.74  -0.11   3.6875  -0.1250   -45.0625
738928  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.306089    89.006044  -9.76  -0.72  -0.19   0.1250  -0.6875   -46.5625
738929  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.311593    89.006044  -9.77  -0.65  -0.31   3.9375   0.3125   -46.5625
738930  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.315506    89.006044  -9.74  -0.62  -0.18   1.2500  -0.3125   -46.1875
738931  61f87f357d6217b5ed17047d  imove.mrt@gmail.com  65.353829    89.006044  -9.75  -0.73  -0.08   4.5000   0.2500   -46.1875
Name: user_id, Length: 15322, dtype: float64

In [9]:
pd.read_csv('/content/Sord_analysis/Activity_files/Sitting.csv')

                                                                                                                  id  ...                   updatedAt
565228 61f87f357d6217b5ed17047d imove.mrt@gmail.com 654.127565  9.696321  -1.58  0.58 -9.97   0.0000 -0.2500  0.5625  ...   2022-02-22 05:34:42.21+00
565229 61f87f357d6217b5ed17047d imove.mrt@gmail.com 654.132046  9.696321  -1.54  0.65 -10.04  0.0625  0.3125  0.5625  ...  2022-02-22 05:34:42.231+00
565230 61f87f357d6217b5ed17047d imove.mrt@gmail.com 654.133634  9.696321  -1.53  0.65 -9.62   0.8750 -0.6250  0.2500  ...  2022-02-22 05:34:42.235+00
565231 61f87f357d6217b5ed17047d imove.mrt@gmail.com 654.134599  9.696321  -1.59  0.49 -9.74  -1.0625  0.0000  0.3750  ...  2022-02-22 05:34:42.237+00
565232 61f87f357d6217b5ed17047d imove.mrt@gmail.com 654.135389  10.037504 -1.42  0.69 -9.84  -0.3125  0.3125  0.5625  ...  2022-02-22 05:34:42.244+00
...                                                                                                              ...  ...                         ...
613642 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2424.346166 12.163309  1.99 -0.10 -9.52   0.6250 -1.0625 -1.3750  ...   2022-02-22 06:08:29.18+00
613643 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2424.348354 11.882637  2.09  0.09 -10.09 -2.6250 -1.8125 -1.5625  ...  2022-02-22 06:08:29.182+00
613644 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2424.490624 11.882637  2.07  0.13 -9.91  -0.8750 -2.3750 -1.5625  ...  2022-02-22 06:08:29.185+00
613645 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2424.494827 11.882637  1.90  0.27 -9.60   3.3125 -1.5625 -1.1875  ...  2022-02-22 06:08:29.187+00
613646 61f87f357d6217b5ed17047d imove.mrt@gmail.com 2424.497505 11.882637  2.07  0.01 -9.87  -3.0625 -1.1875  1.6875  ...   2022-02-22 06:08:29.19+00

[45702 rows x 9 columns]

In [10]:
pd.read_csv('/content/Sord_analysis/Activity_files/raw_new_test_data.csv')

          id  ...                 updatedAt
0     458813  ...  2022-02-14T01:32:45.325Z
1     458814  ...  2022-02-14T01:32:45.332Z
2     458815  ...  2022-02-14T01:32:45.340Z
3     458816  ...  2022-02-14T01:32:45.348Z
4     458817  ...  2022-02-14T01:32:45.363Z
...      ...  ...                       ...
8235  471154  ...  2022-02-14T02:41:44.566Z
8236  471155  ...  2022-02-14T02:41:44.569Z
8237  471156  ...  2022-02-14T02:41:44.571Z
8238  471157  ...  2022-02-14T02:41:44.574Z
8239  471158  ...  2022-02-14T02:41:44.576Z

[8240 rows x 9 columns]